[package]
name = "dupes-cli-test-support"
version.workspace = true
edition = { workspace = true }
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version = { workspace = true }
publish = false

[lints]
workspace = true

[dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
strict-test-support = { workspace = true }
thiserror = { workspace = true }
